services:
  domain_config_ui.negotiator:
    class: Drupal\domain_config_ui\DomainConfigUINegotiator
    tags:
      - { name: persist }
    arguments: ['@request_stack', '@module_handler', '@entity_type.manager', '@config.factory']

  domain_config_ui.overrider:
    class: Drupal\domain_config_ui\DomainConfigUIOverrider
    tags:
      - { name: config.factory.override, priority: -150}
    arguments: ['@config.storage']
